const $=id=>document.getElementById(id);let me=null;
async function api(url,opts={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.message||'Request failed');return d}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function table(headers,rows){return `<table class="work-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
async function init(){try{me=(await api('/api/auth/me')).user;$('welcome').textContent=`Welcome, ${me.name}`;$('roleLine').textContent=me.isAdmin?'Administrator access':`${me.role} account`;$('notice').textContent='Signed in. Workspace data is loaded from the server.';if(me.isAdmin){$('adminArea').classList.remove('hidden');await loadAdminSummary();await loadAdminArtists();await loadAdminUsers()}else if(me.role==='artist'){$('artistArea').classList.remove('hidden');$('slotDate').min=new Date().toISOString().slice(0,10);await loadArtistBookings();await loadNotifications()}else{$('notice').textContent='This workspace is for artist and administrator accounts. Customer accounts can use booking history on the home page.'}}catch(e){$('notice').textContent='Please log in with your artist or administrator account first. Then reopen this page.'}}
$('logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'})}finally{location.href='/'}};
$('availabilityForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/artist/availability',{method:'POST',body:JSON.stringify({date:$('slotDate').value,time:$('slotTime').value,available:$('slotAction').value==='available'})});$('availabilityResult').textContent=d.message;await loadArtistBookings()}catch(err){$('availabilityResult').textContent=err.message}};
async function loadArtistBookings(){try{const d=await api('/api/bookings/mine');const rows=d.bookings.map(b=>[esc(b.id),esc(`${b.date} ${b.time}`),esc(b.service),esc(b.status),`<button class="work-btn" onclick="bookingAction('${esc(b.id)}','accept')">Accept</button><button class="work-btn secondary" onclick="bookingAction('${esc(b.id)}','reject')">Reject</button><button class="work-btn secondary" onclick="bookingAction('${esc(b.id)}','complete')">Complete</button>`]);$('artistBookings').innerHTML=rows.length?table(['Reference','Appointment','Service','Status','Actions'],rows):'<p class="muted">No bookings yet.</p>'}catch(e){$('artistBookings').textContent=e.message}}
async function bookingAction(id,action){try{const d=await api(`/api/artist/bookings/${encodeURIComponent(id)}/status`,{method:'POST',body:JSON.stringify({action})});$('notice').textContent=d.message;await loadArtistBookings();await loadNotifications()}catch(e){$('notice').textContent=e.message}}
async function loadNotifications(){try{const d=await api('/api/notifications');$('notifications').innerHTML=d.notifications.length?d.notifications.map(n=>`<p><strong>${esc(n.title)}</strong><br>${esc(n.message)}<br><small>${esc(n.created_at)}</small></p>`).join(''):'<p class="muted">No notifications yet.</p>'}catch(e){$('notifications').textContent=e.message}}
async function loadAdminSummary(){try{const d=await api('/api/admin/summary');$('metrics').innerHTML=Object.entries({Users:d.users,Artists:d.artists,Bookings:d.bookings,'Confirmed bookings':d.confirmed,'Confirmed/completed booking value':`₹${d.revenue}`,'Artists awaiting verification':d.pendingArtists}).map(([k,v])=>`<div class="work-card"><p class="muted">${esc(k)}</p><div class="metric">${esc(v)}</div></div>`).join('')}catch(e){$('notice').textContent=e.message}}
async function loadAdminArtists(){try{const d=await api('/api/admin/artists');const rows=d.artists.map(a=>[esc(a.name),esc(a.email||'Unlinked demo artist'),esc(a.style),a.verified?'Verified':'Not verified',`<button class="work-btn" onclick="verifyArtist('${esc(a.id)}',${!a.verified})">${a.verified?'Unverify':'Verify'}</button>`]);$('adminArtists').innerHTML=table(['Artist','Account','Specialization','Status','Action'],rows)}catch(e){$('adminArtists').textContent=e.message}}
async function verifyArtist(id,verified){try{await api(`/api/admin/artists/${encodeURIComponent(id)}/verify`,{method:'POST',body:JSON.stringify({verified})});await loadAdminArtists();await loadAdminSummary()}catch(e){$('notice').textContent=e.message}}
async function loadAdminUsers(){try{const d=await api('/api/admin/users');const rows=d.users.map(u=>[esc(u.name),esc(u.email),esc(u.role),u.is_active?'Active':'Inactive',u.is_active?`<button class="work-btn secondary" onclick="setUser('${esc(u.id)}',false)">Deactivate</button>`:`<button class="work-btn" onclick="setUser('${esc(u.id)}',true)">Activate</button>`]);$('adminUsers').innerHTML=table(['Name','Email','Role','State','Action'],rows)}catch(e){$('adminUsers').textContent=e.message}}
async function setUser(id,active){try{await api(`/api/admin/users/${encodeURIComponent(id)}/status`,{method:'POST',body:JSON.stringify({active})});await loadAdminUsers()}catch(e){$('notice').textContent=e.message}}
async function loadAdminBookings(){try{const d=await api('/api/admin/bookings');$('adminBookings').innerHTML=table(['ID','Artist','Service','Date','Amount','Status'],d.bookings.map(b=>[esc(b.id),esc(b.artist_name),esc(b.service),esc(`${b.date} ${b.time}`),`₹${esc(b.amount)}`,esc(b.status)]))}catch(e){$('adminBookings').textContent=e.message}}
async function loadAdminReports(){try{const d=await api('/api/admin/reports');$('adminReports').innerHTML='<h4>By booking status</h4>'+table(['Status','Count','Amount'],d.byStatus.map(x=>[esc(x.status),x.count,`₹${x.amount}`]))+'<h4>Monthly summary</h4>'+table(['Month','Bookings','Paid value'],d.monthly.map(x=>[esc(x.month),x.bookings,`₹${x.paid_amount}`]))+`<p>Reviews: ${d.reviews} · Contact messages: ${d.contacts}</p>`}catch(e){$('adminReports').textContent=e.message}}
init();